from google.cloud import bigquery

SCHEMA_CLEAN_TRIPS = [
    bigquery.SchemaField("event_id", "STRING", mode="REQUIRED"),
    bigquery.SchemaField("event_time", "TIMESTAMP", mode="REQUIRED"),
    bigquery.SchemaField("ingestion_time", "TIMESTAMP", mode="REQUIRED"),
    bigquery.SchemaField("vendor_id", "INT64"),
    bigquery.SchemaField("rate_code_id", "INT64"),
    bigquery.SchemaField("passenger_count", "INT64"),
    bigquery.SchemaField("trip_type", "INT64"),
    bigquery.SchemaField("payment_type", "INT64"),
    bigquery.SchemaField("pickup_datetime", "TIMESTAMP"),
    bigquery.SchemaField("dropoff_datetime", "TIMESTAMP"),
    bigquery.SchemaField("store_and_fwd_flag", "STRING"),
    bigquery.SchemaField("pu_location_id", "INT64"),
    bigquery.SchemaField("do_location_id", "INT64"),
    bigquery.SchemaField("trip_distance", "FLOAT64"),
    bigquery.SchemaField("fare_amount", "FLOAT64"),
    bigquery.SchemaField("extra", "FLOAT64"),
    bigquery.SchemaField("mta_tax", "FLOAT64"),
    bigquery.SchemaField("tip_amount", "FLOAT64"),
    bigquery.SchemaField("tolls_amount", "FLOAT64"),
    bigquery.SchemaField("improvement_surcharge", "FLOAT64"),
    bigquery.SchemaField("congestion_surcharge", "FLOAT64"),
    bigquery.SchemaField("cbd_congestion_fee", "FLOAT64"),
    bigquery.SchemaField("total_amount", "FLOAT64"),
    bigquery.SchemaField("pickup_date", "DATE"),
    bigquery.SchemaField("pickup_hour", "INT64"),
    bigquery.SchemaField("pickup_day_name", "STRING"),
    bigquery.SchemaField("is_weekend", "BOOL"),
    bigquery.SchemaField("trip_duration_minutes", "INT64"),
    bigquery.SchemaField("time_period", "STRING"),
    bigquery.SchemaField("payment_label", "STRING"),
    bigquery.SchemaField("store_and_fwd_flag_label", "STRING"),
    bigquery.SchemaField("_loaded_at", "TIMESTAMP", mode="NULLABLE"),
    bigquery.SchemaField("_data_source", "STRING", mode="NULLABLE"),
]


SCHEMA_QUARANTINE_TRIPS = [
    bigquery.SchemaField("event_id", "STRING", mode="NULLABLE"),
    bigquery.SchemaField("event_time", "TIMESTAMP", mode="NULLABLE"),
    bigquery.SchemaField("ingestion_time", "TIMESTAMP", mode="NULLABLE"),
    bigquery.SchemaField("vendor_id", "INT64"),
    bigquery.SchemaField("rate_code_id", "INT64"),
    bigquery.SchemaField("passenger_count", "INT64"),
    bigquery.SchemaField("trip_type", "INT64"),
    bigquery.SchemaField("payment_type", "INT64"),
    bigquery.SchemaField("pickup_datetime", "TIMESTAMP"),
    bigquery.SchemaField("dropoff_datetime", "TIMESTAMP"),
    bigquery.SchemaField("store_and_fwd_flag", "STRING"),
    bigquery.SchemaField("pu_location_id", "INT64"),
    bigquery.SchemaField("do_location_id", "INT64"),
    bigquery.SchemaField("trip_distance", "FLOAT64"),
    bigquery.SchemaField("fare_amount", "FLOAT64"),
    bigquery.SchemaField("extra", "FLOAT64"),
    bigquery.SchemaField("mta_tax", "FLOAT64"),
    bigquery.SchemaField("tip_amount", "FLOAT64"),
    bigquery.SchemaField("tolls_amount", "FLOAT64"),
    bigquery.SchemaField("improvement_surcharge", "FLOAT64"),
    bigquery.SchemaField("congestion_surcharge", "FLOAT64"),
    bigquery.SchemaField("cbd_congestion_fee", "FLOAT64"),
    bigquery.SchemaField("total_amount", "FLOAT64"),
    bigquery.SchemaField("is_valid", "BOOL"),
    bigquery.SchemaField("is_complete_record", "BOOL"),
    bigquery.SchemaField("is_valid_distance", "BOOL"),
    bigquery.SchemaField("is_valid_fare", "BOOL"),
    bigquery.SchemaField("is_valid_passenger_count", "BOOL"),
    bigquery.SchemaField("is_valid_location", "BOOL"),
    bigquery.SchemaField("amount_mismatch", "BOOL"),
    bigquery.SchemaField("quarantine_reason", "STRING"),
    bigquery.SchemaField("raw_payload", "STRING", mode="NULLABLE"),
    bigquery.SchemaField("dq_checked_at", "TIMESTAMP"),
    bigquery.SchemaField("_loaded_at", "TIMESTAMP", mode="NULLABLE"),
    bigquery.SchemaField("_data_source", "STRING", mode="NULLABLE"),
]
