name: CI - dbt

on:
  push:
    branches: [dev]
    paths: ["dbt/**"]
  pull_request:
    branches: [main]
    paths: ["dbt/**"]

defaults:
  run:
    working-directory: ./dbt

jobs:
  dbt-ci:
    runs-on: ubuntu-latest
    env:
      GCP_PROJECT_ID: jcdeah-009
      BQ_DATASET_RAW: cp3_agungnugraha_raw
      BQ_DATASET_STAGING: cp3_agungnugraha_staging
      BQ_DATASET_INTERMEDIATE: cp3_agungnugraha_intermediate
      BQ_DATASET_MARTS: cp3_agungnugraha_marts
      BQ_DATASET_CI: cp3_agungnugraha_ci
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r ../requirements-dbt.txt

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          create_credentials_file: true

      - name: dbt debug
        run: dbt debug --target ci

      - name: dbt compile
        run: dbt compile --target ci

      - name: dbt test
        if: github.event_name == 'pull_request'
        run: dbt test --target ci