name: CI - Terraform

on:
  push:
    branches: [dev]
    paths: ["infra/terraform/**"]
  pull_request:
    branches: [main]
    paths: ["infra/terraform/**"]

permissions:
  contents: read

concurrency:
  group: terraform-state
  cancel-in-progress: false

defaults:
  run:
    working-directory: ./infra/terraform

jobs:
  terraform-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.15.9"

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        if: github.event_name == 'pull_request'
        run: terraform plan -no-color