name: Terraform CD

on:
  push:
    branches: [main]
    paths: ['terraform/**']

jobs:
  deploy:
    name: Deploy Infrastructure
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    env:
      TF_VAR_project_id: "jcdeah-009"
      TF_VAR_region: "asia-southeast2"
      TF_VAR_resource_prefix: "cp3-agungnugraha"

    steps:
      - uses: actions/checkout@v4

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve